import { BUCKET, clean, cleanupInbox, ensureAccount, json, profileDto, requireUser, rid, sb, settingsDto, usernameify, getInboxSettings, inboxSettingsDto } from './shared.ts';

export async function handleAccount(req:Request,path:string){
  if(path==='/api/account'&&req.method==='GET'){
    const a=await requireUser(req);if(a.error)return a.error;const {profile,settings}=await ensureAccount(a.user);
    const {data:inboxes,error}=await sb.from('inboxes').select('*').eq('creator_key',`auth:${a.user.id}`).order('created_at',{ascending:false});if(error)throw error;
    const ids=(inboxes||[]).map((i:any)=>i.id);const counts=new Map<string,number>();const settingMap=new Map<string,any>();
    if(ids.length){const [mr,sr]=await Promise.all([sb.from('messages').select('inbox_id').in('inbox_id',ids),sb.from('inbox_settings').select('*').in('inbox_id',ids)]);if(mr.error)throw mr.error;if(sr.error)throw sr.error;for(const row of mr.data||[])counts.set(row.inbox_id,(counts.get(row.inbox_id)||0)+1);for(const s of sr.data||[])settingMap.set(s.inbox_id,s);}
    const fr=await sb.from('friendships').select('id').or(`requester_id.eq.${a.user.id},addressee_id.eq.${a.user.id}`).eq('status','accepted');if(fr.error)throw fr.error;
    return json({user:{id:a.user.id,email:a.user.email},profile:profileDto(profile,true),settings:settingsDto(settings),stats:{inboxes:(inboxes||[]).length,totalMessages:[...counts.values()].reduce((x,y)=>x+y,0),friends:(fr.data||[]).length},billing:{plan:profileDto(profile,true)?.plan||'free',premiumPriceNgn:500,paymentsEnabled:false},inboxes:await Promise.all((inboxes||[]).map(async(i:any)=>({id:i.id,slug:i.slug,displayName:i.display_name,handle:i.handle,createdAt:i.created_at,messageCount:counts.get(i.id)||0,settings:inboxSettingsDto(settingMap.get(i.id)||await getInboxSettings(i.id),true)})))});
  }
  if(path==='/api/account/profile'&&req.method==='PATCH'){
    const a=await requireUser(req);if(a.error)return a.error;await ensureAccount(a.user);const body=await req.json().catch(()=>({}));const displayName=clean(body.displayName,60);const username=usernameify(body.username);const bio=clean(body.bio,240);if(!displayName)return json({error:'Enter a display name.'},400);if(!/^[a-z0-9_]{3,24}$/.test(username))return json({error:'Username must be 3–24 letters, numbers or underscores.'},400);const exists=await sb.from('profiles').select('user_id').eq('username',username).neq('user_id',a.user.id).maybeSingle();if(exists.error)throw exists.error;if(exists.data)return json({error:'That username is taken.'},409);const r=await sb.from('profiles').update({display_name:displayName,username,bio,updated_at:new Date().toISOString()}).eq('user_id',a.user.id).select().single();if(r.error)throw r.error;return json({profile:profileDto(r.data,true)});
  }
  if(path==='/api/account/avatar'&&req.method==='POST'){
    const a=await requireUser(req);if(a.error)return a.error;const {profile}=await ensureAccount(a.user);const form=await req.formData();const file=form.get('avatar');if(!(file instanceof File)||!file.size)return json({error:'Choose an image.'},400);const type=String(file.type||'').toLowerCase().split(';')[0];if(!/^image\/(jpeg|png|webp)$/.test(type))return json({error:'Use a JPEG, PNG or WebP image.'},400);if(file.size>5*1024*1024)return json({error:'Profile picture must be 5 MB or smaller.'},413);const ext=type==='image/png'?'png':type==='image/webp'?'webp':'jpg';const avatarPath=`avatars/${a.user.id}/${rid('avatar_')}.${ext}`;const up=await sb.storage.from(BUCKET).upload(avatarPath,file,{contentType:type,upsert:false});if(up.error)throw up.error;if(profile.avatar_path)await sb.storage.from(BUCKET).remove([profile.avatar_path]);const r=await sb.from('profiles').update({avatar_path:avatarPath,updated_at:new Date().toISOString()}).eq('user_id',a.user.id).select().single();if(r.error){await sb.storage.from(BUCKET).remove([avatarPath]);throw r.error;}return json({profile:profileDto(r.data,true)});
  }
  if(path==='/api/account/avatar'&&req.method==='DELETE'){
    const a=await requireUser(req);if(a.error)return a.error;const {profile}=await ensureAccount(a.user);if(profile.avatar_path)await sb.storage.from(BUCKET).remove([profile.avatar_path]);const r=await sb.from('profiles').update({avatar_path:null,updated_at:new Date().toISOString()}).eq('user_id',a.user.id).select().single();if(r.error)throw r.error;return json({profile:profileDto(r.data,true)});
  }
  if(path==='/api/account/settings'&&req.method==='PATCH'){
    const a=await requireUser(req);if(a.error)return a.error;await ensureAccount(a.user);const b=await req.json().catch(()=>({}));const patch:any={updated_at:new Date().toISOString()};if(['system','light','dark'].includes(b.theme))patch.theme=b.theme;for(const [k,c] of [['discoverable','discoverable'],['allowFriendRequests','allow_friend_requests'],['showActivity','show_activity'],['browserNotifications','browser_notifications']] as const)if(typeof b[k]==='boolean')patch[c]=b[k];const r=await sb.from('user_settings').update(patch).eq('user_id',a.user.id).select().single();if(r.error)throw r.error;return json({settings:settingsDto(r.data)});
  }
  if(path==='/api/account/analytics'&&req.method==='GET'){
    const a=await requireUser(req);if(a.error)return a.error;const {profile}=await ensureAccount(a.user);if(!profileDto(profile,true)?.premium)return json({error:'PICNYM Premium required.'},402);const {data:inboxes,error}=await sb.from('inboxes').select('id').eq('creator_key',`auth:${a.user.id}`);if(error)throw error;const ids=(inboxes||[]).map((i:any)=>i.id);if(!ids.length)return json({days:[],uniqueAnonymousSenders:0});const since=new Date(Date.now()-30*86400000).toISOString();const q=await sb.from('messages').select('created_at,sender_key').in('inbox_id',ids).gte('created_at',since);if(q.error)throw q.error;const byDay=new Map<string,number>();const senders=new Set<string>();for(const x of q.data||[]){const d=String(x.created_at).slice(0,10);byDay.set(d,(byDay.get(d)||0)+1);if(x.sender_key)senders.add(x.sender_key);}return json({days:[...byDay].map(([date,count])=>({date,count})),uniqueAnonymousSenders:senders.size,note:'Anonymous analytics never disclose sender identity, exact location, IP address or device fingerprint.'});
  }
  if(path==='/api/account'&&req.method==='DELETE'){
    const a=await requireUser(req);if(a.error)return a.error;const {data:inboxes,error}=await sb.from('inboxes').select('*').eq('creator_key',`auth:${a.user.id}`);if(error)throw error;for(const i of inboxes||[])await cleanupInbox(i);const {data:p}=await sb.from('profiles').select('avatar_path').eq('user_id',a.user.id).maybeSingle();if(p?.avatar_path)await sb.storage.from(BUCKET).remove([p.avatar_path]);const del=await sb.auth.admin.deleteUser(a.user.id);if(del.error)throw del.error;return json({ok:true});
  }
  return null;
}
