import { CORE, SERVICE, areFriends, authUser, clean, cleanupInbox, coreJson, ensureAccount, getInboxSettings, hash, inboxBySlug, inboxSettingsDto, json, ownerAllowed, profileDto, publicProfileForCreator, requireInbox, requireUser, rid, sb, senderProfiles, slugify } from './shared.ts';

export async function handleInbox(req:Request,path:string){
  let m:RegExpMatchArray|null;
  if(path==='/api/inboxes'&&req.method==='POST'){
    const a=await requireUser(req);if(a.error)return a.error;const {profile}=await ensureAccount(a.user);const count=await sb.from('inboxes').select('id',{count:'exact',head:true}).eq('creator_key',`auth:${a.user.id}`);if(count.error)throw count.error;const premium=profileDto(profile,true)?.premium;const limit=premium?30:5;if((count.count||0)>=limit)return json({error:`Your ${premium?'Premium':'free'} plan supports up to ${limit} inboxes.`},403);const {response,data}=await coreJson(req,path);if(response.ok&&data?.id)await sb.from('inbox_settings').upsert({inbox_id:data.id});return json(data,response.status);
  }
  if((m=path.match(/^\/api\/inboxes\/([^/]+)$/))&&req.method==='GET'){
    const slug=decodeURIComponent(m[1]);const {response,data}=await coreJson(req,path);if(!response.ok||!data)return json(data||{error:'Inbox unavailable.'},response.status);const inbox=await inboxBySlug(slug);if(!inbox)return json({error:'Inbox not found.'},404);return json({...data,profile:await publicProfileForCreator(inbox),settings:inboxSettingsDto(await getInboxSettings(inbox.id),false)},200);
  }
  if((m=path.match(/^\/api\/inboxes\/([^/]+)\/settings$/))&&req.method==='PATCH'){
    const slug=decodeURIComponent(m[1]);const o=await requireInbox(slug,req);if(o.error)return o.error;const b=await req.json().catch(()=>({}));const hiddenWords=Array.isArray(b.hiddenWords)?[...new Set(b.hiddenWords.map((x:any)=>clean(x,60).toLowerCase()).filter(Boolean))].slice(0,100):undefined;const patch:any={updated_at:new Date().toISOString()};for(const [k,c] of [['paused','paused'],['registeredOnly','registered_only'],['friendsOnly','friends_only'],['allowImages','allow_images'],['allowVoice','allow_voice'],['allowPolls','allow_polls']] as const)if(typeof b[k]==='boolean')patch[c]=b[k];if(hiddenWords)patch.hidden_words=hiddenWords;const r=await sb.from('inbox_settings').upsert({inbox_id:o.inbox.id,...patch},{onConflict:'inbox_id'}).select().single();if(r.error)throw r.error;return json({settings:inboxSettingsDto(r.data,true)});
  }
  if((m=path.match(/^\/api\/inboxes\/([^/]+)$/))&&req.method==='PATCH'){
    const slug=decodeURIComponent(m[1]);const o=await requireInbox(slug,req);if(o.error)return o.error;const b=await req.json().catch(()=>({}));const desired=slugify(b.slug||slug);const displayName=clean(b.displayName||o.inbox.display_name,40);if(!desired)return json({error:'Enter a valid link name.'},400);if(!displayName)return json({error:'Enter a display name.'},400);const exists=await sb.from('inboxes').select('id').eq('slug',desired).neq('id',o.inbox.id).maybeSingle();if(exists.error)throw exists.error;if(exists.data)return json({error:'That link is already taken.'},409);const r=await sb.from('inboxes').update({slug:desired,handle:desired,display_name:displayName}).eq('id',o.inbox.id).select().single();if(r.error)throw r.error;return json({id:r.data.id,slug:r.data.slug,displayName:r.data.display_name,handle:r.data.handle,createdAt:r.data.created_at,profile:await publicProfileForCreator(r.data),settings:inboxSettingsDto(await getInboxSettings(r.data.id),true)});
  }
  if((m=path.match(/^\/api\/inboxes\/([^/]+)$/))&&req.method==='DELETE'){
    const slug=decodeURIComponent(m[1]);const o=await requireInbox(slug,req);if(o.error)return o.error;await cleanupInbox(o.inbox);return json({ok:true});
  }
  if((m=path.match(/^\/api\/inboxes\/([^/]+)\/messages$/))&&req.method==='GET'){
    const slug=decodeURIComponent(m[1]);const o=await requireInbox(slug,req);if(o.error)return o.error;const {response,data}=await coreJson(req,path);if(!response.ok||!data)return json(data||{error:'Could not load inbox.'},response.status);const ids=(data.messages||[]).map((x:any)=>x.id);let raw:any[]=[];if(ids.length){const r=await sb.from('messages').select('id,sender_user_id,sender_revealed,favorite,archived,is_public').in('id',ids);if(r.error)throw r.error;raw=r.data||[];}const rawMap=new Map(raw.map(x=>[x.id,x]));const pm=await senderProfiles(raw);data.messages=(data.messages||[]).map((x:any)=>{const r=rawMap.get(x.id)||{};return {...x,favorite:Boolean(r.favorite),archived:Boolean(r.archived),isPublic:Boolean(r.is_public),senderProfile:r.sender_revealed&&r.sender_user_id?pm.get(r.sender_user_id)||null:null};});data.inbox={...data.inbox,profile:await publicProfileForCreator(o.inbox),settings:inboxSettingsDto(await getInboxSettings(o.inbox.id),true)};return json(data,200);
  }
  if((m=path.match(/^\/api\/inboxes\/([^/]+)\/messages$/))&&req.method==='POST'){
    const slug=decodeURIComponent(m[1]);const inbox=await inboxBySlug(slug);if(!inbox)return json({error:'Inbox not found.'},404);const s=await getInboxSettings(inbox.id);if(s.paused)return json({error:'This inbox is paused.'},403);const user=await authUser(req);if(s.registered_only&&!user)return json({error:'Sign in to send to this inbox.'},401);if(s.friends_only){const owner=String(inbox.creator_key||'').startsWith('auth:')?String(inbox.creator_key).slice(5):'';if(!user||!await areFriends(owner,user.id))return json({error:'This inbox only accepts messages from friends.'},403);}const form=await req.formData();const kind=String(form.get('kind')||'text');if(kind==='image'&&!s.allow_images)return json({error:'Images are disabled for this inbox.'},403);if(kind==='voice'&&!s.allow_voice)return json({error:'Voice notes are disabled for this inbox.'},403);if(kind==='poll'&&!s.allow_polls)return json({error:'Polls are disabled for this inbox.'},403);const check=[form.get('text'),form.get('question'),form.get('options')].map(x=>String(x||'').toLowerCase()).join(' ');if((s.hidden_words||[]).some((w:string)=>w&&check.includes(String(w).toLowerCase())))return json({error:'This inbox does not accept that message.'},400);const reveal=String(form.get('revealProfile')||'')==='1'&&Boolean(user);if(reveal&&user)await ensureAccount(user);const response=await fetch(new Request(CORE+path,{method:'POST',headers:req.headers,body:form}));let data:any=null;try{data=await response.json();}catch{return response;}if(response.ok&&data?.id&&reveal&&user){const up=await sb.from('messages').update({sender_user_id:user.id,sender_revealed:true}).eq('id',data.id);if(up.error)console.error('Reveal profile update failed:',up.error.message);}return json(data,response.status);
  }
  return null;
}

export async function handleMessageTools(req:Request,path:string){
  let m:RegExpMatchArray|null;
  if((m=path.match(/^\/api\/messages\/([^/]+)\/state$/))&&req.method==='PATCH'){
    const id=decodeURIComponent(m[1]);const b=await req.json().catch(()=>({}));const mr=await sb.from('messages').select('*').eq('id',id).maybeSingle();if(mr.error)throw mr.error;if(!mr.data)return json({error:'Message not found.'},404);const ir=await sb.from('inboxes').select('*').eq('id',mr.data.inbox_id).maybeSingle();if(ir.error)throw ir.error;if(!await ownerAllowed(ir.data,req))return json({error:'Owner access required.'},403);const patch:any={};if(typeof b.favorite==='boolean')patch.favorite=b.favorite;if(typeof b.archived==='boolean')patch.archived=b.archived;if(typeof b.isPublic==='boolean'){if(b.isPublic&&!clean(mr.data.reply,700))return json({error:'Answer the message before publishing it.'},400);patch.is_public=b.isPublic;}const r=await sb.from('messages').update(patch).eq('id',id).select('favorite,archived,is_public').single();if(r.error)throw r.error;return json({ok:true,favorite:r.data.favorite,archived:r.data.archived,isPublic:r.data.is_public});
  }
  if((m=path.match(/^\/api\/messages\/([^/]+)\/report$/))&&req.method==='POST'){
    const id=decodeURIComponent(m[1]);const b=await req.json().catch(()=>({}));const mr=await sb.from('messages').select('*').eq('id',id).maybeSingle();if(mr.error)throw mr.error;if(!mr.data)return json({error:'Message not found.'},404);const ir=await sb.from('inboxes').select('*').eq('id',mr.data.inbox_id).maybeSingle();if(ir.error)throw ir.error;if(!await ownerAllowed(ir.data,req))return json({error:'Owner access required.'},403);const user=await authUser(req);const r=await sb.from('reports').insert({id:rid('rep_'),message_id:id,reporter_user_id:user?.id||null,reporter_key:await hash(`${SERVICE.slice(0,20)}|${req.headers.get('x-forwarded-for')||''}|${req.headers.get('user-agent')||''}`),target_type:'message',target_id:id,reason:clean(b.reason||'Other',80),details:clean(b.details,1000),status:'open'});if(r.error)throw r.error;return json({ok:true},201);
  }
  return null;
}
