import { json, profileDto, profileForUserIds, requireUser, rid, sb, usernameify } from './shared.ts';

export async function handleSocial(req:Request,path:string,url:URL){
  if(path==='/api/users/search'&&req.method==='GET'){
    const a=await requireUser(req);if(a.error)return a.error;const q=usernameify(url.searchParams.get('q'));if(q.length<3)return json({users:[]});const r=await sb.from('profiles').select('*').ilike('username',`%${q}%`).neq('user_id',a.user.id).limit(20);if(r.error)throw r.error;const ids=(r.data||[]).map((p:any)=>p.user_id);let allow=new Map<string,boolean>();if(ids.length){const s=await sb.from('user_settings').select('user_id,discoverable').in('user_id',ids);if(s.error)throw s.error;allow=new Map((s.data||[]).map((x:any)=>[x.user_id,x.discoverable!==false]));}return json({users:(r.data||[]).filter((p:any)=>allow.get(p.user_id)!==false).map((p:any)=>({...profileDto(p),userId:p.user_id}))});
  }
  if(path==='/api/friends'&&req.method==='GET'){
    const a=await requireUser(req);if(a.error)return a.error;const r=await sb.from('friendships').select('*').or(`requester_id.eq.${a.user.id},addressee_id.eq.${a.user.id}`).order('created_at',{ascending:false});if(r.error)throw r.error;const ids=[...new Set((r.data||[]).flatMap((f:any)=>[f.requester_id,f.addressee_id]).filter((id:string)=>id!==a.user.id))];const pm=await profileForUserIds(ids);const incoming:any[]=[],outgoing:any[]=[],accepted:any[]=[];for(const f of r.data||[]){const other=f.requester_id===a.user.id?f.addressee_id:f.requester_id;const item={id:f.id,profile:pm.get(other)};if(f.status==='accepted')accepted.push(item);else if(f.addressee_id===a.user.id)incoming.push(item);else outgoing.push(item);}return json({incoming,outgoing,accepted});
  }
  if(path==='/api/friends/request'&&req.method==='POST'){
    const a=await requireUser(req);if(a.error)return a.error;const b=await req.json().catch(()=>({}));const username=usernameify(b.username);const p=await sb.from('profiles').select('*').eq('username',username).maybeSingle();if(p.error)throw p.error;if(!p.data||p.data.user_id===a.user.id)return json({error:'User not found.'},404);const set=await sb.from('user_settings').select('allow_friend_requests').eq('user_id',p.data.user_id).maybeSingle();if(set.error)throw set.error;if(set.data?.allow_friend_requests===false)return json({error:'This user is not accepting friend requests.'},403);const pair=[a.user.id,p.data.user_id].sort().join(':');const existing=await sb.from('friendships').select('*').eq('pair_key',pair).maybeSingle();if(existing.error)throw existing.error;if(existing.data)return json({ok:true,status:existing.data.status});const i=await sb.from('friendships').insert({id:rid('fr_'),requester_id:a.user.id,addressee_id:p.data.user_id,status:'pending'});if(i.error)throw i.error;return json({ok:true,status:'pending'},201);
  }
  let m:RegExpMatchArray|null;
  if((m=path.match(/^\/api\/friends\/([^/]+)\/accept$/))&&req.method==='POST'){
    const a=await requireUser(req);if(a.error)return a.error;const other=decodeURIComponent(m[1]);const pair=[a.user.id,other].sort().join(':');const r=await sb.from('friendships').update({status:'accepted',updated_at:new Date().toISOString()}).eq('pair_key',pair).eq('addressee_id',a.user.id).eq('status','pending').select().maybeSingle();if(r.error)throw r.error;if(!r.data)return json({error:'Friend request not found.'},404);return json({ok:true});
  }
  if((m=path.match(/^\/api\/friends\/([^/]+)$/))&&req.method==='DELETE'){
    const a=await requireUser(req);if(a.error)return a.error;const other=decodeURIComponent(m[1]);const pair=[a.user.id,other].sort().join(':');const r=await sb.from('friendships').delete().eq('pair_key',pair);if(r.error)throw r.error;return json({ok:true});
  }
  if((m=path.match(/^\/api\/profiles\/([a-z0-9_]+)$/))&&req.method==='GET'){
    const username=decodeURIComponent(m[1]).toLowerCase();const p=await sb.from('profiles').select('*').eq('username',username).maybeSingle();if(p.error)throw p.error;if(!p.data)return json({error:'Profile not found.'},404);const setting=await sb.from('user_settings').select('discoverable').eq('user_id',p.data.user_id).maybeSingle();if(setting.error)throw setting.error;if(setting.data?.discoverable===false)return json({error:'Profile not found.'},404);const fr=await sb.from('friendships').select('id').or(`requester_id.eq.${p.data.user_id},addressee_id.eq.${p.data.user_id}`).eq('status','accepted');if(fr.error)throw fr.error;const own=await sb.from('inboxes').select('id').eq('creator_key',`auth:${p.data.user_id}`);if(own.error)throw own.error;const ids=(own.data||[]).map((i:any)=>i.id);let posts:any[]=[];if(ids.length){const msg=await sb.from('messages').select('*').eq('is_public',true).neq('reply','').in('inbox_id',ids).order('created_at',{ascending:false}).limit(50);if(msg.error)throw msg.error;posts=(msg.data||[]).map((x:any)=>({id:x.id,kind:x.kind,text:x.text,imageUrl:x.image_path?sb.storage.from('phx-media').getPublicUrl(x.image_path).data.publicUrl:null,voiceUrl:x.voice_path?sb.storage.from('phx-media').getPublicUrl(x.voice_path).data.publicUrl:null,reply:x.reply,createdAt:x.created_at,poll:null}));}return json({profile:profileDto(p.data),stats:{friends:(fr.data||[]).length,publicAnswers:posts.length},posts});
  }
  return null;
}
